### ISSUE TITLE
Getting error by using vjoy.update()

### ISSUE THREAD

**Issue by ghost** [tidzo/pyvjoy#1]
Getting this error
```
Traceback (most recent call last):
  File "main.py", line 71, in <module>
    vjoy.update()
  File "C:\Users\Jersh\Desktop\JoyconDrivers\pyvjoy\vjoydevice.py", line 65, in update
    return self._sdk.UpdateVJD(self.rID, self.data)
  File "C:\Users\Jersh\Desktop\JoyconDrivers\pyvjoy\_sdk.py", line 145, in UpdateVJD
    return _vj.UpdateVJD(rID, data)
OSError: exception: access violation writing 0x00000001
```

**Comment by LadyAelita** [comment]
Same for me. Well, almost the same to be precise - it says "WindowsError", instead of "OSError".

Is it possible that an older version of vJoyInterface.dll has to be used?

**Comment by arpruss** [comment]
For me the address it's writing is 2, not 1.
